name: SleepScorer
channels:
  - conda-forge
dependencies:
  - jupyter
  - holoviews
  - python
  - scipy
  - bokeh
  - matplotlib=3.1.1
  - opencv
  - mne
  - pandas
  - plotnine
  - pylint
  - dask
  - natsort
